2024-01-25 19:09:50,481 - utils_main - INFO - Start testing eval methods
2024-01-26 05:45:22,889 - utils_main - INFO - Start testing eval methods
2024-01-26 05:50:39,994 - utils_main - INFO - Start testing eval methods
2024-01-26 05:50:42,167 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,168 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,169 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,169 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,170 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,171 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,171 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
    ^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,172 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,172 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,173 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,174 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,174 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-3.5
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,175 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,175 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,176 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,176 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,177 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,177 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,178 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,179 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,179 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,180 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,180 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,181 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gpt-4
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,181 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,182 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,182 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,183 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,184 - utils_main - ERROR - Failed Questionnaire: BFI, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,184 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: choose, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,185 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,185 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,186 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,186 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_convert_adjoption_anonymous_api, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,187 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_batch_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:50:42,188 - utils_main - ERROR - Failed Questionnaire: 16Personalities, Eval Method: interview_assess_collective_anonymous, Repeat Times: 3, Agent LLM: gwen, Eval LLM: gemini
Traceback (most recent call last):
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/test_eval_methods.py", line 36, in <module>
    result = personality_assessment(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 581, in personality_assessment
    character_agent = build_character_agent(character, agent_type, agent_llm)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/yunzex/InCharacter-Role-Playing-Agents-Can-Capture-Character-Personalities-/code/personality_tests.py", line 165, in build_character_agent
    character_agent.llm.chat.temperature = 0
                                          ^
UnboundLocalError: cannot access local variable 'character_agent' where it is not associated with a value
2024-01-26 05:52:24,900 - utils_main - INFO - Start testing eval methods
